force-app/main/default/objects/LogEntryEvent__e/LogEntryEvent__e.object-meta.xml
<CustomObject>
    <description>Platform Event object used by Nebula Logger for publishing debug and exception log entries</description>
    <label>Log Entry Event</label>
    <pluralLabel>Log Entry Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogEntryEvent__e/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <label>Exception Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

vdmc-core-app/main/default/objects/LogEntryEvent__e/fields/ExceptionStackTrace__c.field-meta.xml
<CustomField>
    <fullName>ExceptionStackTrace__c</fullName>
    <label>Exception Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEntryEvent__e/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <label>Log Level</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

vdmc-core-app/main/default/objects/LogEntryEvent__e/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <label>Transaction ID</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/src/Logger/Business/LogEventPublisher.cls
public with sharing class LogEventPublisher implements LogEventPublisherInterface {
    
    private final String TRANSACTION_ID;
    private List<LogEntryEvent__e> logEvents;
    
    public LogEventPublisher() {
        this.TRANSACTION_ID = getTransactionId();
        this.logEvents = new List<LogEntryEvent__e>();
    }

    public void logError(Exception ex) {
        LogEntryEvent__e log = new LogEntryEvent__e();
        
        log.TransactionId__c = this.TRANSACTION_ID;
        log.ExceptionMessage__c = ex.getMessage();
        log.ExceptionStackTrace__c = ex.getStackTraceString();
        log.LogLevel__c = LogLevel.ERROR.name();

        this.logEvents.add(log);
    } 

    public void logWarning(String warning) {
        LogEntryEvent__e log = new LogEntryEvent__e();
        
        log.TransactionId__c = this.TRANSACTION_ID;
        log.ExceptionMessage__c = warning;
        log.LogLevel__c = LogLevel.WARNING.name();

        this.logEvents.add(log);
    }

    public void logInfo(String info) {
        LogEntryEvent__e log = new LogEntryEvent__e();
        
        log.TransactionId__c = this.TRANSACTION_ID;
        log.ExceptionMessage__c = info;
        log.LogLevel__c = LogLevel.INFO.name();

        this.logEvents.add(log);
    }

    public void save() {
        
        Eventbus.publish(this.logEvents);
        this.logEvents.clear();

    }

    private String getTransactionId() {
        return String.isNotBlank(System.Request.getCurrent().getRequestId())?
            System.Request.getCurrent().getRequestId(): new Uuid().getValue();
    }
}