force-app/main/default/objects/Logger_Setting__mdt/Logger_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Contains all settings for the logger-system including Sentry-Api-Key</description>
    <label>Logger Setting</label>
    <pluralLabel>Logger Setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/Logger_Setting__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enable/disable Sentry Connection</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Logger_Setting__mdt/fields/Sentry_Key__c.field-meta.xml
<CustomField>
    <fullName>Sentry_Key__c</fullName>
    <description>Auth Key of Sentry</description>
    <label>Sentry Key</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

vdmc-core-app/main/default/objects/Logger_Setting__mdt/fields/Sentry_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Sentry_Project_Id__c</fullName>
    <description>Project-Id of Sentry</description>
    <label>Sentry Project-Id</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger_Setting__mdt/fields/Sentry_Url__c.field-meta.xml
<CustomField>
    <fullName>Sentry_Url__c</fullName>
    <description>Contains the sentry auth url</description>
    <inlineHelpText>Url</inlineHelpText>
    <label>Sentry Api Url</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

vdmc-core-app/main/default/objects/Logger_Setting__mdt/fields/Sentry_Version__c.field-meta.xml
<CustomField>
    <fullName>Sentry_Version__c</fullName>
    <description>Version of Sentry-Api</description>
    <label>Sentry Version-Id</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <defaultValue>7</defaultValue>
</CustomField>

vdmc-core-app/main/default/classes/src/Logger/Persistence/LoggerConfigReadRepository.cls
public class LoggerConfigReadRepository {
    
    private Logger_Setting__mdt setting;

    public LoggerConfigReadRepository(OrganizationType type) {
        this.setting = Logger_Setting__mdt.getInstance(type.name().toLowerCase());
    }

    public Boolean isActive() {
        return (Boolean) this.setting.get('Active__c');
    }

    public String getSentryUrl() {
        return (String) this.setting.get('Sentry_Url__c');
    }

    public Integer getSentryVersion() {
        return Integer.valueOf(this.setting.get('Sentry_Version__c'));
    }

    public String getSentryKey() {
        return (String) this.setting.get('Sentry_Key__c');
    }

    public String getSentryProjectId() {
        return (String) this.setting.get('Sentry_Project_Id__c');
    }
}